"""whisper_task-cmd

Revision ID: 68d1e65b0e2a
Revises: cde085d03ca2
Create Date: 2023-04-12 17:07:58.937309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d1e65b0e2a'
down_revision = 'cde085d03ca2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whisper_tasks', sa.Column('cmd', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'whisper_tasks', ['fullpath'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whisper_tasks', type_='unique')
    op.drop_column('whisper_tasks', 'cmd')
    # ### end Alembic commands ###
