"""remove-incoming_file-foreignkey

Revision ID: 993542c06a4d
Revises: a0de8479b83c
Create Date: 2023-04-23 14:07:44.023299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "993542c06a4d"
down_revision = "68d1e65b0e2a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "incoming_files_task_id_fkey", "incoming_files", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "incoming_files_task_id_fkey",
        "incoming_files",
        "whisper_tasks",
        ["task_id"],
        ["id"],
    )
    # ### end Alembic commands ###
